---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: tidepool
  namespace: master
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.auth: glob:master-*
    flux.weave.works/tag.blip: glob:master-*
    flux.weave.works/tag.blob: glob:master-*
    flux.weave.works/tag.data: glob:master-*
    flux.weave.works/tag.export: glob:master-*
    flux.weave.works/tag.gatekeeper: glob:master-*
    flux.weave.works/tag.highwater: glob:master-*
    flux.weave.works/tag.hydrophone: glob:master-*
    flux.weave.works/tag.image: glob:master-*
    flux.weave.works/tag.jellyfish: glob:master-*
    flux.weave.works/tag.mailhog: semver:1.*
    flux.weave.works/tag.messageapi: glob:master-*
    flux.weave.works/tag.migrations: glob:master-*
    flux.weave.works/tag.notification: glob:master-*
    flux.weave.works/tag.seagull: glob:master-*
    flux.weave.works/tag.shoreline: glob:master-*
    flux.weave.works/tag.task: glob:master-*
    flux.weave.works/tag.tidewhisperer: glob:master-*
    flux.weave.works/tag.tools: glob:master-*
    flux.weave.works/tag.user: glob:master-*
spec:
  releaseName: master-tidepool
  chart:
    git: git@github.com:tidepool-org/development
    path: charts/tidepool/0.1.4
    ref: k8s
  values:
    global:
      gateway:
        domain:
          name: integration-test.tidepool.org
        name: gloo
        https:
          enabled: false
        http:
          enabled: true
      mongo:
        enabled: false
      includeSecrets: false
      namespace:
        create: false
    nosqlclient:
      enabled: false
    blip:
      image: tidepool/blip:master-f05cda804cc5ac0d3e002ff7ee7713ac3bf90394
    export:
      enabled: true
      image: tidepool/export:master-17c8de7344eea3d8a404e1c112c2c7f03e88321e
    gatekeeper:
      image: tidepool/gatekeeper:master-ff9239c90d432a251024247380e54123896beb03
    highwater:
      image: tidepool/highwater:master-1a7a0f9ce2af300a9b366b69043afaf28befdb99
    hydrophone:
      image: tidepool/hydrophone:master-5a098f25546a3a2f0e1dfbbc51735589dcf03879
    jellyfish:
      image: tidepool/jellyfish:master-3409448a4dcd8f5de7167c7525c3cd89cedadf95
    messageapi:
      image: tidepool/message-api:master-1087d1378392afaadef077b82af64d0904036c20
    auth:
      image: tidepool/platform-auth:master-3468cb7a3d6f0cf5971a281022586a9462668737
    blob:
      image: tidepool/platform-blob:master-3468cb7a3d6f0cf5971a281022586a9462668737
    data:
      image: tidepool/platform-data:master-3468cb7a3d6f0cf5971a281022586a9462668737
    image:
      image: tidepool/platform-image:master-3468cb7a3d6f0cf5971a281022586a9462668737
    migrations:
      image: tidepool/platform-migrations:master-3468cb7a3d6f0cf5971a281022586a9462668737
    notification:
      enabled: false
      image: tidepool/platform-notification:master-3468cb7a3d6f0cf5971a281022586a9462668737
    task:
      image: tidepool/platform-task:master-3468cb7a3d6f0cf5971a281022586a9462668737
    tools:
      enabled: false
      image: tidepool/platform-tools:master-3468cb7a3d6f0cf5971a281022586a9462668737
    user:
      image: tidepool/platform-user:master-3468cb7a3d6f0cf5971a281022586a9462668737
    seagull:
      image: tidepool/seagull:master-8b9d5288a81f937e16013202876f7167c47a30ac
    shoreline:
      image: tidepool/shoreline:master-b6505c04b001d63c89d36d13de568c63a5eeac6c
    tidewhisperer:
      image: tidepool/tide-whisperer:master-1995cc2dd7f5f3ae0621d82c9716748eab108d60
