---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: tidepool
  namespace: develop
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.auth: glob:develop-*
    flux.weave.works/tag.blip: glob:develop-*
    flux.weave.works/tag.blob: glob:develop-*
    flux.weave.works/tag.data: glob:develop-*
    flux.weave.works/tag.export: glob:develop-*
    flux.weave.works/tag.gatekeeper: glob:develop-*
    flux.weave.works/tag.highwater: glob:develop-*
    flux.weave.works/tag.hydrophone: glob:k8s-*
    flux.weave.works/tag.image: glob:develop-*
    flux.weave.works/tag.jellyfish: glob:develop-*
    flux.weave.works/tag.mailhog: semver:1.*
    flux.weave.works/tag.messageapi: glob:develop-*
    flux.weave.works/tag.migrations: glob:develop-*
    flux.weave.works/tag.notification: glob:develop-*
    flux.weave.works/tag.seagull: glob:develop-*
    flux.weave.works/tag.shoreline: glob:debug-*
    flux.weave.works/tag.task: glob:develop-*
    flux.weave.works/tag.tidewhisperer: glob:develop-*
    flux.weave.works/tag.tools: glob:develop-*
    flux.weave.works/tag.user: glob:develop-*
spec:
  releaseName: develop-tidepool
  chart:
    git: git@github.com:tidepool-org/development
    path: charts/tidepool/0.1.4
    ref: k8s
  values:
    global:
      gateway:
        domain:
          name: integration-test.tidepool.org
        name: gloo
        https:
          enabled: false
        http:
          enabled: true
      mongo:
        enabled: false
      includeSecrets: false
      namespace:
        create: false
    nosqlclient:
      enabled: false
    blip:
      image: tidepool/blip:develop-c22739233fb82443dcb79e9bdf6c1ee03adf1fd0
    export:
      enabled: true
      image: tidepool/export:develop-b00327cf2a986cf4c63aecc9140c1df63c5caa59
    gatekeeper:
      image: tidepool/gatekeeper:develop-9b8e58227a946eae34debbe23f7748d7e9570b79
    highwater:
      image: tidepool/highwater:develop-3f0838c29e726230b616638d97f593ba07607bab
    hydrophone:
      image: tidepool/hydrophone:k8s-1e188f354f9a90a0d04c23e2175dc35546118781
    jellyfish:
      image: tidepool/jellyfish:develop-942156b4166dc5b158bf53fe8826872be62fe44e
    messageapi:
      image: tidepool/message-api:develop-3c23130779e5286a404c439bed49c18186a7711a
    auth:
      image: tidepool/platform-auth:develop-f401ac553fa733b3ecfdf35dae465003d309400e
    blob:
      image: tidepool/platform-blob:develop-f401ac553fa733b3ecfdf35dae465003d309400e
    data:
      image: tidepool/platform-data:develop-f401ac553fa733b3ecfdf35dae465003d309400e
    image:
      image: tidepool/platform-image:develop-f401ac553fa733b3ecfdf35dae465003d309400e
    migrations:
      image: tidepool/platform-migrations:develop-f401ac553fa733b3ecfdf35dae465003d309400e
    notification:
      enabled: false
      image: tidepool/platform-notification:develop-f401ac553fa733b3ecfdf35dae465003d309400e
    task:
      image: tidepool/platform-task:develop-f401ac553fa733b3ecfdf35dae465003d309400e
    tools:
      enabled: false
      image: tidepool/platform-tools:develop-f401ac553fa733b3ecfdf35dae465003d309400e
    user:
      image: tidepool/platform-user:develop-f401ac553fa733b3ecfdf35dae465003d309400e
    seagull:
      image: tidepool/seagull:develop-968e1d2afae10efe9b537637f73777e227df798c
    shoreline:
      image: tidepool/shoreline:debug-5c12cfb915a007ae70a9735b4d04c2a35920ae7f
    tidewhisperer:
      image: tidepool/tide-whisperer:develop-26174c02c95fe1d5b092fea68b7046fd3fc1e798
