apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mongo
  namespace: master
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: master-mongo
  skipDepUpdate: true
  chart:
    git: git@github.com:tidepool-org/development
    path: charts/mongo
    ref: k8s
  values:
    mongo:
      image: mongo:3.2
      persistent: false
      seed: true
