apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gloo
  namespace: gloo-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: gloo
  chart:
    repository: https://storage.googleapis.com/solo-public-helm/
    name: gloo
    version: 0.13.30
  values:
    namespace:
      create: false
    rbac:
      create: true
    crds:
      create: false
    
    settings:
      # if this is set to false, default settings will be created by pods upon boot
      create: false
      integrations:
        knative:
          enabled: false
      # namespaces that Gloo should watch. this includes watches set for pods, services, as well as CRD configuration objects
      watchNamespaces: []
      # the namespace that Gloo should write discovery data (Upstreams)
      writeNamespace: "gloo-system"
    
    gloo:
      deployment:
        image:
          repository: quay.io/solo-io/gloo
          pullPolicy: Always
        xdsPort: 9977
        replicas: 1
        stats: true

    discovery:
      enabled: true
      deployment:
        image:
          repository: quay.io/solo-io/discovery
          pullPolicy: Always
        replicas: 1
        stats: true
    
    gateway:
      enabled: true
      deployment:
        image:
          repository: quay.io/solo-io/gateway
          pullPolicy: Always
        replicas: 1
        stats: true
    
    gatewayProxies:
      gateway-proxy:
        deployment:
          image:
            repository: quay.io/solo-io/gloo-envoy-wrapper
            pullPolicy: Always
          stats: true
          httpPort: 8080
          httpsPort: 8443
          replicas: 1
        service:
          type: ClusterIP
          # clusterIP: None
          httpPort: 80
          httpsPort: 443
    
    ingress:
      enabled: false
