---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: loadbalancer
  namespace: gloo-system
spec:
  releaseName: loadbalancer
  chart:
    git: git@github.com:tidepool-org/development
    path: charts/loadbalancer
    ref: k8s
  values:
    gateway:
      name: gloo
      http:
        enabled: true
      https:
        enabled: true
      hostnames: "*.integration-test.tidepool.org"

