---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: default
spec:
  releaseName: external-dns
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: external-dns
    version: 1.7.9
  values:
    domainfilter: tidepool.org
    provider: aws
    image:
      name: registry.opensource.zalan.do/teapot/external-dns
      pullSecrets: {}
    tag: latest
    awszonetype: public 
    ownerid: external-dns 
    rbac:
      create: true
    logLevel: debug
    aws:
      region: us-west-2
    txtOwnerId: default

