---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: tidepool
  namespace: released
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.shoreline: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.tidewhisperer: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.blip: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.gatekeeper: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.highwater: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.jellyfish: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.mailhog: semver:1.*
    flux.weave.works/tag.export: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.seagull: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.hydrophone: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.messageapi: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.auth: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.blob: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.data: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.image: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.migrations: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.notification: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.task: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.tools: regexp:^v\d+\.\d+\.\d+$
    flux.weave.works/tag.user: regexp:^v\d+\.\d+\.\d+$
spec:
  releaseName: released-tidepool
  chart:
    git: git@github.com:tidepool-org/development
    path: charts/tidepool/0.1.4
    ref: k8s
  values:
    global:
      gateway:
        domain:
          name: integration-test.tidepool.org
        name: gloo
        https:
          enabled: false
        http:
          enabled: true
      mongo:
        enabled: false
      includeSecrets: false
      namespace:
        create: false
    nosqlclient:
      enabled: false
    blip:
      image: tidepool/blip:v1.21.0
    export:
      enabled: true
      image: tidepool/export:v1.3.2
    gatekeeper:
      image: tidepool/gatekeeper:v0.7.2
    highwater:
      image: tidepool/highwater:v0.3.5
    hydrophone:
      image: tidepool/hydrophone:v99.99.100
    jellyfish:
      image: tidepool/jellyfish:v0.12.3
    messageapi:
      image: tidepool/message-api:develop-3c23130779e5286a404c439bed49c18186a7711a
    auth:
      image: tidepool/platform-auth:go11110-89257ec20c2aa8899b76d7b8264619ce55d3f8bb
    blob:
      image: tidepool/platform-blob:go11110-89257ec20c2aa8899b76d7b8264619ce55d3f8bb
    data:
      image: tidepool/platform-data:go11110-89257ec20c2aa8899b76d7b8264619ce55d3f8bb
    image:
      image: tidepool/platform-image:go11110-89257ec20c2aa8899b76d7b8264619ce55d3f8bb
    migrations:
      image: tidepool/platform-migrations:go11110-89257ec20c2aa8899b76d7b8264619ce55d3f8bb
    notification:
      enabled: false
      image: tidepool/platform-notification:go11110-89257ec20c2aa8899b76d7b8264619ce55d3f8bb
    task:
      image: tidepool/platform-task:go11110-89257ec20c2aa8899b76d7b8264619ce55d3f8bb
    tools:
      enabled: false
      image: tidepool/platform-tools:go11110-89257ec20c2aa8899b76d7b8264619ce55d3f8bb
    user:
      image: tidepool/platform-user:go11110-89257ec20c2aa8899b76d7b8264619ce55d3f8bb
    seagull:
      image: tidepool/seagull:v0.7.2
    shoreline:
      image: tidepool/shoreline:v0.14.2
    tidewhisperer:
      image: tidepool/tide-whisperer:v0.13.0
